### ISSUE TITLE
MIDI USB Library w/o Teensy???!

### ISSUE THREAD

**Issue by callen0817** [TravisThatcher/WheelController#1]
Does the MIDIUSB Lbirary work on the Arduino Uno without Teensy? I keep getting an error that "MIDIUSB can only be used with an USB MCU"

**Comment by TravisThatcher** [comment]
I don't believe so - the MIDIUSB library needs an MCU that can talk over usb natively. The Uno uses a serial protocol. My code uses MIDI.h however: https://github.com/FortySevenEffects/arduino_midi_library

**Comment by callen0817** [comment]
aaaaaaaaaaah! man at this point i feel like i need to mail you the parts and pay you to put everything together...hahaha
